// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID        int64
	Title     string
	CreatedAt pgtype.Timestamptz
	Done      pgtype.Bool
}
